/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.panel;

import main.utility.JDBCUtil;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.sql.*;

/**
 *
 * @author bryan
 */
public class PanelPendataanBarang extends javax.swing.JPanel {

    private Connection conn;
    private PreparedStatement stmnt;

    private void updateTable() {
        DefaultTableModel tabel = (DefaultTableModel) jTable1.getModel();
        tabel.setRowCount(0);
        try {
            conn = JDBCUtil.getConnection();
            stmnt = conn.prepareStatement("SELECT * FROM barang;");
            ResultSet rs = stmnt.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String brand = rs.getString("brand");
                String typenVarian = rs.getString("type_and_variant");
                String color = rs.getString("color");
                int stock = rs.getInt("stock");
                int price = rs.getInt("price_out");
                tabel.addRow( new Object[] {id, brand, typenVarian, color, stock, price});
            }

            rs.close(); stmnt.close(); conn.close();

        } catch (SQLException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }

    }

    /**
     * Creates new form PanelPendataanBarang
     */
    public PanelPendataanBarang() {
        initComponents();
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfMerek = new javax.swing.JTextField();
        tfTipenVarian = new javax.swing.JTextField();
        combBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfWarna = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfHarga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        labelStok = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Pendataan Produk");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel2.setText("Id :");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel3.setText("Merek :");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel4.setText("Tipe dan varian :");

        tfId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfIdKeyPressed(evt);
            }
        });

        tfMerek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfMerekKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMerekKeyTyped(evt);
            }
        });

        tfTipenVarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfTipenVarianKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTipenVarianKeyTyped(evt);
            }
        });

        combBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cari", "Hapus" }));
        combBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combBox1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel5.setText("Stok :");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel6.setText("Warna : ");

        tfWarna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfWarnaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfWarnaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N
        jLabel7.setText("Harga jual :");

        tfHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfHargaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfHargaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 2, 15)); // NOI18N
        jLabel8.setText("(1 Juta diwakili 1000)");
        jLabel8.setPreferredSize(new java.awt.Dimension(135, 35));

        labelStok.setFont(new java.awt.Font("Liberation Sans", 0, 15)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Brand", "Tipe & Varian", "Warna", "Stok", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(combBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSimpan)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnReset))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfHarga, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                            .addComponent(tfWarna, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfTipenVarian, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tfMerek, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(labelStok))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStok, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMerek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTipenVarian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfWarna, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            String brand = tfMerek.getText();

            if (brand.isEmpty() || tfTipenVarian.getText().isEmpty() || tfWarna.getText().isEmpty() || tfHarga.getText().isEmpty() ) {
                JOptionPane.showMessageDialog(this, "4 Form diatas harus diisi");
                return;
            }

            String[] returned = {"id"};
            conn = JDBCUtil.getConnection();

            stmnt = conn.prepareStatement("INSERT INTO barang (brand, type_and_variant, color, price_out) " +
                    "VALUES (?, ?, ?, ?);", returned);
            stmnt.setString(1, brand);
            stmnt.setString(2, brand + " " + tfTipenVarian.getText());
            stmnt.setString(3, tfWarna.getText());
            stmnt.setInt(4, Integer.parseInt(tfHarga.getText()));

            int affected = stmnt.executeUpdate();
            if (affected < 1) {
                JOptionPane.showMessageDialog(this, "Data tidak ter-insert");
            } else {
                ResultSet rs = stmnt.getGeneratedKeys();
                if (rs.next()) {
                    // harus by column index
                    JOptionPane.showMessageDialog(this, "Data berhasil di-insert dengan id: " + rs.getInt(1));
                } else {
                    JOptionPane.showMessageDialog(this, "Data berhasil di-insert");
                }
                rs.close();
            }

            stmnt.close(); conn.close();

            tfMerek.setText(""); tfTipenVarian.setText(""); tfWarna.setText(""); tfHarga.setText("");
        } catch (SQLException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void combBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combBox1ActionPerformed
        if (combBox1.getSelectedItem().equals("Cari")) {

            if (tfId.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Form id harus diisi");
                return;
            }

            try {
                conn = JDBCUtil.getConnection();
                stmnt = conn.prepareStatement("SELECT * FROM barang WHERE id = ?;");
                stmnt.setInt(1, Integer.parseInt(tfId.getText()));
                ResultSet rs = stmnt.executeQuery();

                if (rs.next()) {
                    labelStok.setText(String.valueOf(rs.getInt("stock")));
                    tfMerek.setText(rs.getString("brand"));
                    String[] str = rs.getString("type_and_variant").split(" ");
                    // ada bug
                    tfTipenVarian.setText(str[1]);
                    tfWarna.setText(rs.getString("color"));
                    tfHarga.setText(String.valueOf(rs.getInt("price_out")));
                } else {
                    JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
                }

                rs.close(); stmnt.close(); conn.close();

            } catch (SQLException exc) {
                exc.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error");
            }
        } else if (combBox1.getSelectedItem().equals("Hapus")) {
            System.out.println("Hapus");
        }

    }//GEN-LAST:event_combBox1ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        tfId.setText(""); tfMerek.setText(""); tfTipenVarian.setText(""); tfWarna.setText(""); tfHarga.setText(""); labelStok.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void tfMerekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMerekKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMerekKeyTyped

    private void tfTipenVarianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTipenVarianKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTipenVarianKeyTyped

    private void tfWarnaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfWarnaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfWarnaKeyTyped

    private void tfHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHargaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaKeyTyped

    private void tfMerekKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMerekKeyPressed
        if (evt.getKeyChar() == '\n') {
            tfTipenVarian.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfId.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfTipenVarian.requestFocus();
        }
    }//GEN-LAST:event_tfMerekKeyPressed

    private void tfIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfMerek.requestFocus();
        }
    }//GEN-LAST:event_tfIdKeyPressed

    private void tfTipenVarianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTipenVarianKeyPressed
        if (evt.getKeyChar() == '\n') {
            tfWarna.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfMerek.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfWarna.requestFocus();
        }
    }//GEN-LAST:event_tfTipenVarianKeyPressed

    private void tfWarnaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfWarnaKeyPressed
        if (evt.getKeyChar() == '\n') {
            tfHarga.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfTipenVarian.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tfHarga.requestFocus();
        }
    }//GEN-LAST:event_tfWarnaKeyPressed

    private void tfHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfHargaKeyPressed
        if (evt.getKeyChar() == '\n') {
            btnSimpanActionPerformed(null);
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            tfWarna.requestFocus();
        }
    }//GEN-LAST:event_tfHargaKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> combBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelStok;
    private javax.swing.JTextField tfHarga;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfMerek;
    private javax.swing.JTextField tfTipenVarian;
    private javax.swing.JTextField tfWarna;
    // End of variables declaration//GEN-END:variables
}
