/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.panel;

import main.utility.JDBCUtil;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import java.sql.*;

/**
 *
 * @author bryan
 */
public class PanelPenjualanBarang extends javax.swing.JPanel {

    private Connection conn;
    private PreparedStatement stmnt;
    private int price, total, totalPrice, money, back, pengadaanBarangId, karyawanId, pelangganId;
    private String brand, typenVariant, color;
    private final String GET_BARANG_AND_PENGADAAN_BARANG =
            "SELECT brg.brand, brg.type_and_variant, brg.color, brg.price_out, pngdn_brg.quantity_decrement AS stock, pngdn_brg.id AS id " +
            "FROM pengadaan_barang pngdn_brg " +
            "INNER JOIN barang brg " +
            "ON pngdn_brg.barang_id = brg.id " +
            "WHERE pngdn_brg.id = ?;";

    private final String GET_KARYAWAN_BY_ID =
            "SELECT * FROM karyawan WHERE id = ?;";

    /**
     * Creates new form PanelPenjualanBarang
     */
    public PanelPenjualanBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tfJumlahBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfUangPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfKembalian = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfIdKaryawan = new javax.swing.JTextField();
        btnCekKaryawan = new javax.swing.JButton();
        tfPelanggan = new javax.swing.JTextField();
        btnCekPelanggan = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 300));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Penjualan Barang");

        jLabel2.setText("Id barang :");

        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        textArea1.setColumns(20);
        textArea1.setRows(5);
        jScrollPane1.setViewportView(textArea1);

        jLabel3.setText("Jumlah barang :");

        tfJumlahBarang.setEditable(false);

        jLabel4.setText("Uang pelanggan :");

        tfUangPelanggan.setEditable(false);
        tfUangPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUangPelangganKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUangPelangganKeyTyped(evt);
            }
        });

        jLabel5.setText("Kembalian :");

        tfKembalian.setEditable(false);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jLabel6.setText("Id karyawan :");

        jLabel7.setText("Id pelanggan :");

        btnCekKaryawan.setText("Cek");
        btnCekKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekKaryawanActionPerformed(evt);
            }
        });

        tfPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPelangganActionPerformed(evt);
            }
        });

        btnCekPelanggan.setText("Cek");
        btnCekPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekPelangganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCekPelanggan))
                            .addComponent(tfUangPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCekKaryawan))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCek)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfIdKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCekKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCekPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUangPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        if (tfId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Form id harus diisi");
            return;
        }

        try {
            conn = JDBCUtil.getConnection();
            stmnt = conn.prepareStatement(GET_BARANG_AND_PENGADAAN_BARANG);
            stmnt.setInt(1, Integer.parseInt(tfId.getText()));
            ResultSet rs = stmnt.executeQuery();

            if (rs.next()) {
                price = rs.getInt("price_out") * 1000;
                pengadaanBarangId = rs.getInt("id");
                brand = rs.getString("brand");
                typenVariant = rs.getString("type_and_variant");
                color = rs.getString("color");

                int stock = rs.getInt("stock");
                String status = (stock < 1) ? "Barang dengan id " + pengadaanBarangId + " tidak tersedia" : "Barang dengan id " + pengadaanBarangId + "\n \t  tersedia sebanyak "  + stock + " barang";
                String data = "\n Merek\t: " + brand +
                        "\n Tipe & varian\t: " + typenVariant +
                        "\n Warna\t: " + color +
                        "\n Harga jual\t: " + price +
                        "\n Status\t: " + status;
                textArea1.setText(data);
                tfJumlahBarang.setEditable(true);
                tfUangPelanggan.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }

            rs.close(); stmnt.close(); conn.close();

        } catch (SQLException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (pengadaanBarangId == 0 || karyawanId == 0 || pelangganId == 0) {
            JOptionPane.showMessageDialog(this, "Harap cek barang terlebih dulu");
            return;
        }
//        total = Integer.parseInt(tfJumlahBarang.getText());
//        totalPrice = total * price;
//        money = Integer.parseInt(tfUangPelanggan.getText());
//        back = money - totalPrice;
        
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Popup().setVisible(true);
            }
        });
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tfUangPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUangPelangganKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tfUangPelangganKeyTyped

    private void tfUangPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUangPelangganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfJumlahBarang.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Form jumlah barang harus diisi");
                return;
            }
            int money = Integer.parseInt(tfUangPelanggan.getText());
            int back =  money - ((price * 1000) * Integer.parseInt(tfJumlahBarang.getText()));
            if (back > 0) {
                tfKembalian.setText(String.valueOf(back));
            }
        }
    }//GEN-LAST:event_tfUangPelangganKeyPressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCekKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekKaryawanActionPerformed
        try {
            conn = JDBCUtil.getConnection();
            stmnt = conn.prepareStatement(GET_KARYAWAN_BY_ID);
            stmnt.setInt(1, Integer.parseInt(tfIdKaryawan.getText()));
            ResultSet rs = stmnt.executeQuery();

            if (rs.next()) {
                String data = "\n Nama\t: " +  rs.getString("nama") +
                        "\n Jabatan\t: " + rs.getString("jabatan");
                textArea1.setText(data);
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }

            rs.close(); stmnt.close(); conn.close();

        } catch (SQLException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnCekKaryawanActionPerformed

    private void tfPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPelangganActionPerformed

    private void btnCekPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCekPelangganActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCekKaryawan;
    private javax.swing.JButton btnCekPelanggan;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfIdKaryawan;
    private javax.swing.JTextField tfJumlahBarang;
    private javax.swing.JTextField tfKembalian;
    private javax.swing.JTextField tfPelanggan;
    private javax.swing.JTextField tfUangPelanggan;
    // End of variables declaration//GEN-END:variables
}
