/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.panel;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.sql.*;

/**
 *
 * @author bryan
 */
public class PanelPenjualanBarang extends javax.swing.JPanel {

    private Connection conn;
    private PreparedStatement stmnt;
    private int price;
    // tambahkan quantity masuk, dan quantity decrement di tabel pengadaan
    private final String GET_BARANG_AND_PENGADAAN_BARANG =
            "SELECT brg.brand, brg.type_and_variant, brg.color, brg.stock, brg.price_out " +
            "FROM pengadaan_barang pngdn_brg " +
            "INNER JOIN barang brg " +
            "ON pngdn_brg.barang_id = brg.id " +
            "WHERE pngdn_brg.id = ?;";

    private Connection getConnection() throws SQLException {
        String hostNPort = "103.171.85.233:3306";
        String database = "PboDB";
        String user = "strukdat";
        String password = "Passwordegan**1234";

        return DriverManager.getConnection("jdbc:mysql://" + hostNPort + "/" + database + "?useSSL=false", user, password);
    }

    /**
     * Creates new form PanelPenjualanBarang
     */
    public PanelPenjualanBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        tfJumlahBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfUangPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfKembalian = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 300));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel1.setText("Penjualan Barang");

        jLabel2.setText("Id barang :");

        tfId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdActionPerformed(evt);
            }
        });

        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        textArea1.setColumns(20);
        textArea1.setRows(5);
        jScrollPane1.setViewportView(textArea1);

        jLabel3.setText("Jumlah barang :");

        tfJumlahBarang.setEditable(false);
        tfJumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJumlahBarangActionPerformed(evt);
            }
        });

        jLabel4.setText("Uang pelanggan :");

        tfUangPelanggan.setEditable(false);
        tfUangPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfUangPelangganKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfUangPelangganKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUangPelangganKeyTyped(evt);
            }
        });

        jLabel5.setText("Kembalian :");

        tfKembalian.setEditable(false);
        tfKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfKembalianActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCek))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfKembalian, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(tfUangPelanggan, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCek, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUangPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        if (tfId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Form id harus diisi");
            return;
        }

        try {
            conn = getConnection();
            stmnt = conn.prepareStatement(GET_BARANG_AND_PENGADAAN_BARANG);
            stmnt.setInt(1, Integer.parseInt(tfId.getText()));
            ResultSet rs = stmnt.executeQuery();

            if (rs.next()) {
                String data = "\n Merek\t: " + rs.getString("brand") +
                        "\n Tipe & varian\t: " + rs.getString("type_and_variant") +
                        "\n Warna\t: " + rs.getString("color") +
                        "\n Stok\t: " + rs.getInt("stock") +
                        "\n Harga jual\t: " + (rs.getInt("price_out") * 1000);
                textArea1.setText(data);
                price = rs.getInt("price_out");
                tfJumlahBarang.setEditable(true);
                tfUangPelanggan.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan");
            }

            rs.close(); stmnt.close(); conn.close();

        } catch (SQLException exc) {
            exc.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnCekActionPerformed

    private void tfJumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJumlahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJumlahBarangActionPerformed

    private void tfKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfKembalianActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (price == 0) {
            JOptionPane.showMessageDialog(this, "Harap cek barang terlebih dulu");
            return;
        }
        System.out.println(price);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tfUangPelangganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUangPelangganKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUangPelangganKeyReleased

    private void tfUangPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUangPelangganKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_tfUangPelangganKeyTyped

    private void tfUangPelangganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUangPelangganKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (tfJumlahBarang.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Form jumlah barang harus diisi");
                return;
            }
            int money = Integer.parseInt(tfUangPelanggan.getText());
            int back =  money - ((price * 1000) * Integer.parseInt(tfJumlahBarang.getText()));
            if (back > 0) {
                tfKembalian.setText(String.valueOf(back));
            }
        }
    }//GEN-LAST:event_tfUangPelangganKeyPressed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfJumlahBarang;
    private javax.swing.JTextField tfKembalian;
    private javax.swing.JTextField tfUangPelanggan;
    // End of variables declaration//GEN-END:variables
}
