/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.frame;

import main.panel.*;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author bryan
 */
public class MainUI extends javax.swing.JFrame {
    public void showJOptionToMainFrame(Object message) {
        JOptionPane.showMessageDialog(this, message);
    }

    public void setPanel(Component component) {
        scrollPane.setViewportView(component);
    }

    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        scrollPane.setViewportView(new PanelPendataanBarang(this));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        menuBarang = new javax.swing.JMenuItem();
        menuPelanggan = new javax.swing.JMenuItem();
        menuKaryawan = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuPengadaan = new javax.swing.JMenuItem();
        menuPenjualan = new javax.swing.JMenuItem();
        menuRekapPengadaan = new javax.swing.JMenuItem();
        menuRekapPenjualan = new javax.swing.JMenuItem();
        menuHistori = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko HP");

        scrollPane.setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Pendataan");

        menuBarang.setText("Produk");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        jMenu2.add(menuBarang);

        menuPelanggan.setText("Pelanggan");
        menuPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPelangganActionPerformed(evt);
            }
        });
        jMenu2.add(menuPelanggan);

        menuKaryawan.setText("Karyawan");
        menuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(menuKaryawan);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Transaksi");

        menuPengadaan.setText("Pengadaan barang");
        menuPengadaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPengadaanActionPerformed(evt);
            }
        });
        jMenu1.add(menuPengadaan);

        menuPenjualan.setText("Penjualan barang");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(menuPenjualan);

        menuRekapPengadaan.setText("Rekap pengadaan");
        menuRekapPengadaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRekapPengadaanActionPerformed(evt);
            }
        });
        jMenu1.add(menuRekapPengadaan);

        menuRekapPenjualan.setText("Rekap penjualan");
        menuRekapPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRekapPenjualanActionPerformed(evt);
            }
        });
        jMenu1.add(menuRekapPenjualan);

        menuHistori.setText("Histori pelanggan");
        menuHistori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuHistoriActionPerformed(evt);
            }
        });
        jMenu1.add(menuHistori);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKaryawanActionPerformed
        scrollPane.setViewportView(new Karyawan_UI());
    }//GEN-LAST:event_menuKaryawanActionPerformed

    private void menuRekapPengadaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRekapPengadaanActionPerformed
        scrollPane.setViewportView(new PanelRekapPengadaan());
    }//GEN-LAST:event_menuRekapPengadaanActionPerformed

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        scrollPane.setViewportView(new PanelPendataanBarang(this));
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuPengadaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPengadaanActionPerformed
        scrollPane.setViewportView(new PanelPengadaanBarang(this));
    }//GEN-LAST:event_menuPengadaanActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        scrollPane.setViewportView(new PanelPenjualanBarang(this));
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPelangganActionPerformed
        scrollPane.setViewportView(new PanelPelanggan());
    }//GEN-LAST:event_menuPelangganActionPerformed

    private void menuRekapPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRekapPenjualanActionPerformed
        scrollPane.setViewportView(new PanelRekapPenjualanBarang());
    }//GEN-LAST:event_menuRekapPenjualanActionPerformed

    private void menuHistoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuHistoriActionPerformed
        scrollPane.setViewportView(new PanelHistory(this));
    }//GEN-LAST:event_menuHistoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenuItem menuHistori;
    private javax.swing.JMenuItem menuKaryawan;
    private javax.swing.JMenuItem menuPelanggan;
    private javax.swing.JMenuItem menuPengadaan;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenuItem menuRekapPengadaan;
    private javax.swing.JMenuItem menuRekapPenjualan;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
